# pnpm workspace configuration
# Liste des packages gérés par pnpm.
# Chaque entrée doit pointer vers un dossier contenant un package.json.
packages:
  # apps/* inclut apps/backend, apps/frontend, etc.
  - 'apps/*'
